### PR TITLE
Add Resources from Azure quickstart template

### PR DESCRIPTION
**Pull request by scottpas**
This should resolve Issue #8 

Copied the resources from https://github.com/Azure/RDS-Templates/tree/master/DSC/Configuration/xRemoteDesktopSessionHost/DSCResources and updated the OS version check to use the `Test-xRemoteDesktopSessionHostOsRequirement` function.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)

### CODE REVIEW

**Comment by scottpas** [comment]
I took a cursory look at the other resources and they appear to be from the 1.0.1 release of xRemoteDesktopSessionHost. I'm also working on addressing your other comments now

---







*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-:-LC9YO1B4RAD4r5QVUTf:brvpt0t)*

**Comment by scottpas** [comment]
*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9BTjKCjxx2EmnzV0h:-LC9ZbuH35nujYk-mwqZ:b-k7tpj9) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The documentation (README.md) should be updated with these resources.
</blockquote></details>

Added descriptions for the new resources

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by scottpas** [comment]
*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9BfI-1GHlG3qoB7Va:-LC9ZhEi2Yh-XT2aQsHG:b-3zxs49) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please update with an entry of this change in the change log, under the Unreleased section in the file README.md.
</blockquote></details>

Done. Let me know if you think I should add a link to the quickstart files

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by ld0614** [comment]
Hi Guys, the code looks good, just to let you know that I'm just in final testing of a similar patch which includes a full copy from the quickstart repository as well as further fixes to enable HA deployments.  My view on unit tests would be to get something merged into dev so that people can start taking advantage of the new functionality but make unit tests the next major priority for the whole repo

**Comment by scottpas** [comment]
*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9B2pm0rSdLW_C9s7z:-LC9k2fA5U2eQiJ_PQfB:b-vi0r1g) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Are you up to adding at least unit tests for these resources?  See [tests guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
</blockquote></details>

I've added tests for xRDServer and xRDGatewayConfiguration

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by johlju** [comment]
@ld0614 can you add to issue https://github.com/PowerShell/xRemoteDesktopSessionHost/issues/8 which resources you are working on. When this PR is merged you will have to base your work on the new dev branch.  🙂

**Comment by johlju** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9BfI-1GHlG3qoB7Va:-LCDIygT39xTTTzTrqi0:bfk1me5) (no related file):*
<details><summary><i>Previously, scottpas (Scott Paschke) wrote…</i></summary><blockquote>

Done. Let me know if you think I should add a link to the quickstart files
</blockquote></details>

Please add a link, and give the authors credit (as per Michael's suggestion in the issue). 

---

*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9B2pm0rSdLW_C9s7z:-LCDM1Dp7srupdo5JVxl:bv9pncl) (no related file):*
<details><summary><i>Previously, scottpas (Scott Paschke) wrote…</i></summary><blockquote>

I've added tests for xRDServer and xRDGatewayConfiguration
</blockquote></details>

Would you be up to adding tests for xRDLicenseConfiguration too?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by johlju** [comment]
@ld0614 would you mind continue drive the review of this PR, if so I will focus on reviews in other repos instead? 🙂

**Comment by ld0614** [comment]
@johlju Yes I'm happy to lead on this review, apologies that I've been a little silent around here for a few months.

**Comment by ld0614** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9BfI-1GHlG3qoB7Va:-LCF1Hf59nlSxHqlr2LL:b-jo5q38) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a link, and give the authors credit (as per Michael's suggestion in the issue). 
</blockquote></details>

The change should be made under the unreleased section as versions are incremented during the release process, to be slightly picky Add should also probably be Added as it should be read as if the change was made in the past

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by johlju** [comment]
@ld0614 No worries. I know we all have a lot to do! 😃

**Comment by danielboth** [comment]
Thanks @scottpas for this PR. I think the resources added here are very valuable! I still see some work to be done though, like adding tests for xRDLicenseConfiguration, do you plan to continue work on this? I'm happy to contribute by adding the tests if you like.

**Comment by scottpas** [comment]
@danielboth Sorry for the delay, I pushed up my changes to xRDLicenseConfiguration.

It appears that LicenseMode is a required parameter for the Set-RDLicenseConfiguration cmdlet, so I set it to mandatory for the Set/Test-TargetResource functions. On Get-TargetResource, it doesn't use LicenseMode at all, but it will fail the Script Resource Schema Validation pester tests if the parameters are not the same for all the TargetResource functions; however, the DSC best practice guide says that Get-TargetResource shouldn't contain any unused (or non-mandatory) parameters -- anyone have thoughts on this?

**Comment by ld0614** [comment]
As the resource is a mandatory one I would suggest that you include it and just pass the response back, alternatively you could remove the requirement on mandatory and just set a default.  By the looks of the code defaulting to notconfigured might be a good idea?

**Comment by scottpas** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9BfI-1GHlG3qoB7Va:-LDw4A0KBd7CqlgWyyEr:b-896fix) (no related file):*
<details><summary><i>Previously, ld0614 (Leo D'Arcy) wrote…</i></summary><blockquote>

The change should be made under the unreleased section as versions are incremented during the release process, to be slightly picky Add should also probably be Added as it should be read as if the change was made in the past
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-LC9B2pm0rSdLW_C9s7z:-LDw4CMXDQw1FaRG8K_7:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would you be up to adding tests for xRDLicenseConfiguration too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by ld0614** [comment]
:lgtm: @johlju are you happy for me to merge?

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-:-LDw4yDtAjUbtnbA2Hxm:b56hgj)*

**Comment by ld0614** [comment]
@scottpas I've just merged another PR into xRemoteDesktopSessionHost which is now causing a conflict on your readme file, would you be able to resolve the conflict please?

**Comment by ld0614** [comment]
@scottpas thanks for handling the merge conflict, as the previous PR also included significant testing your PR is now failing as your only testing 30% of your changes.  Would you be able to add additional tests to your test files to test different scenarios please?  Currently the bar is to include at least 66% coverage of changes.  You can identify which lines aren't currently being tested [here](https://codecov.io/gh/PowerShell/xRemoteDesktopSessionHost/compare/316e32f923592e523c918a209b9e85f23eea67bf...1a02627af80db286f064df2e0b088d3481210762/diff).  An example of test code can now be located [here](https://github.com/PowerShell/xRemoteDesktopSessionHost/blob/dev/tests/unit/MSFT_xRDSessionCollectionConfiguration.tests.ps1)

**Comment by danielboth** [comment]
Hi @scottpas, I noticed the issue of missing tests on the new resources and decided to add a few. I currently added those to https://github.com/danielboth/xRemoteDesktopSessionHost/tree/azure-quickstart-resources-tests. I also did one change in there where I renamed the LicenseServers parameter on the xRDLicenseConfiguration to LicenseServer (singular) as it should be in PowerShell. 

Hope you can continue on this PR?

**Comment by scottpas** [comment]
Thanks for writing the tests @danielboth! I merged them in and everything looks happy now.

**Comment by danielboth** [comment]
Indeed, look good now, thanks! @ld0614 can we merge this one in now?

**Comment by ld0614** [comment]
:lgtm: We've just got to wait on @johlju to complete his comments and then I'll merge, thanks for the additional tests.  

---

Review status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @johlju)

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-:-LF3gjmZAcMqguYD7d0Y:b5q2omv)*

**Comment by ld0614** [comment]
Reviewed 2 of 5 files at r4, 1 of 6 files at r5, 2 of 12 files at r9, 5 of 5 files at r11.
Review status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33)*

**Comment by johlju** [comment]
:lgtm:

@scottpas @danielboth awesome work both of you! @danielboth Thank you for helping writing the tests! :bowing_man: 

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/33#-:-LFGfr7r1U-fFYgBesGh:b8ugvhj)*

**Comment by ld0614** [comment]
Sorry for the delayed merge, thanks @scottpas and @danielboth for your contribution 😄

**Pull request merged**
