### PR TITLE
Update Module to Meet current PSSA guidelines

### PR DESCRIPTION
**Pull request by ld0614**
There are a number of issues with the current module when run through the standard battery of tests in Appveyor.  This PR goes through and fixes these.  They are all very minor, mainly formatting and Parameter changes and there shouldn't be any functional impact to the module.  

I have also updated the copyright information as per the [guidelines](https://github.com/PowerShell/DscResources/blob/master/Maintainers.md#change-copyright-information) and fixed the failing unit tests while bringing them in line with the latest testing template.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/29)

### CODE REVIEW

**Comment by johlju** [comment]
Thought I would help out and review this one for you. I did not do any style review comments on this since I don't know if you are there yet. Let me know if you want me to do that.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[appveyor.yml, line 1 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyLLrcR38PMRqRhelQ:-KyyLLrdrH0rwpEUu4pe:bniqci) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/appveyor.yml#L1)):*
> ```YAML
> #---------------------------------# 
> ```

Non-blocking. You could simplify this by using the default model of the test framework, which do all this, see example here:
https://github.com/PowerShell/xComputerManagement/blob/dev/appveyor.yml
and
https://github.com/PowerShell/xSQLServer/blob/dev/appveyor.yml (same as xComputerManagement, but do some initial configuration on the build worker)

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyMWPActZrQiCsrnTV:-KyyMWPActZrQiCsrnTW:b21vspj) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/README.md#L3)):*
> ```Markdown
> # xRemoteDesktopSessionHost
> 
> [Build status](https://ci.appveyor.com/project/PowerShell/xremotedesktopsessionhost/branch/master)
> ```

Non-blocking, You could use the Branches section from the other repos, see xComputerManagement as an example. If you resolve the above comment, then you can add CodeCov badge as well.
https://github.com/PowerShell/xComputerManagement/blob/dev/README.md

---

*[tests/unit/xRemoteDesktopSessionHost.tests.ps1, line 26 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyPuSpU5fJzK7uCXht:-KyyPuSpU5fJzK7uCXhu:b-a2qy2n) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/tests/unit/xRemoteDesktopSessionHost.tests.ps1#L26)):*
> ```PowerShell
> }
> 
> function Invoke-TestCleanup {
> ```

Missing `Restore-TestEnvironment -TestEnvironment $TestEnvironment`here. Is there a reason that we could not have it in this test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-:-KyyQ95kJbjctakGyEZK:b1xxtqd)*

**Comment by ld0614** [comment]
Thanks @johlju for the review, I've not completed a style update yet, I think the best thing to do is run that as a separate PR due to the number of updates involved.  Happy to take direction and keep this PR open if that's the better approach though

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[appveyor.yml, line 1 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyLLrcR38PMRqRhelQ:-KzJ_yu9Y7u22tEI7Ent:b-896fix) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/appveyor.yml#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking. You could simplify this by using the default model of the test framework, which do all this, see example here:
https://github.com/PowerShell/xComputerManagement/blob/dev/appveyor.yml
and
https://github.com/PowerShell/xSQLServer/blob/dev/appveyor.yml (same as xComputerManagement, but do some initial configuration on the build worker)
</blockquote></details>

Done.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyMWPActZrQiCsrnTV:-KzJ_xMBT0x4c42qy0D4:b-896fix) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/README.md#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking, You could use the Branches section from the other repos, see xComputerManagement as an example. If you resolve the above comment, then you can add CodeCov badge as well.
https://github.com/PowerShell/xComputerManagement/blob/dev/README.md
</blockquote></details>

Done.

---

*[tests/unit/xRemoteDesktopSessionHost.tests.ps1, line 26 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-KyyPuSpU5fJzK7uCXht:-KzJSeFWoXMAzhmQ5fQf:b-o09sg0) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/420bb6910cda53d476dcfc99524373f5682fced2/tests/unit/xRemoteDesktopSessionHost.tests.ps1#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missing `Restore-TestEnvironment -TestEnvironment $TestEnvironment`here. Is there a reason that we could not have it in this test?
</blockquote></details>

Yes, this script doesn't actually run Initialize-TestEnvironment and therefore the restore-TestEnvironment fails.  The tests themselves need a significant amount of work on them but I was going to keep that as a separate piece of work due to the amount of work required.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-:-KzJ_zwBy1zKAdV9s6sy:b-rtxaci)*

**Comment by johlju** [comment]
:lgtm:

No problem, happy to help. :smile:  You are welcome to tag me if you want a second pair of eyes on a PR. 

I agree it's better to do separate PR's for the style and other improvements.  

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/29#-:-KzUZj4gJ2fsfCQrI7ke:bed0xf)*

**Comment by ld0614** [comment]
Thanks @johlju What type of merge should this be done under?

**Comment by johlju** [comment]
It’s up to you and maybe dependent on circumstances. Also depends if you want to retain the working branch commit history.  I usually use “Squash commit” Which squashed all the working branch commits (PR commits) into a new commit. As commit title I normally use PR title, and for the commit message I normally use the text in the change log from the PR.

**Pull request merged**
