### PR TITLE
Fixed Collection Name Max Length (Fixes #60)

### LINKED ISSUE #60: Collectionname max 15 charaters, why?

### PR DESCRIPTION
**Pull request by bendunne**
#### Pull Request (PR) description
Corrects Collection Name variable max length from 15 characters to 80 characters in the xRDSessionCollection and xRDSessionCollectionConfiguration resources

#### This Pull Request (PR) fixes the following issues
- Fixes #60 

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/61)

### CODE REVIEW

**Comment by bendunne** [comment]
@johlju @ld0614 Hi, Would you mind merging this one?

**Comment by johlju** [comment]
@bendunne This was set to 15 char limit because of the issue https://github.com/PowerShell/xRemoteDesktopSessionHost/issues/10, is this not an issue anymore?

**Comment by johlju** [comment]
Is/was this a limitation in an older operating system?

**Comment by bendunne** [comment]
> Is/was this a limitation in an older operating system?

I don't know if there was but I've tested on 2012 R2 with WMF 5.1 and 2016 and both work. I didn't test on 2008R2 as the module 'RemoteDesktop' doesn't exist nor are there 'Collections' in 2008R2

**Comment by bendunne** [comment]
> > Is/was this a limitation in an older operating system?
> 
> I don't know if there was but I've tested on 2012 R2 with WMF 5.1 and 2016 and both work. I didn't test on 2008R2 as the module 'RemoteDesktop' doesn't exist nor are there 'Collections' in 2008R2

I've also updated the App CollectionName max length which isn't an issue either

**Comment by johlju** [comment]
Then I suggest we remove the length validation altogether from all the resources. That is remove the line `[ValidateLength(1,80)]` throughout.

I will review after that.

**Comment by bendunne** [comment]
> Then I suggest we remove the length validation altogether from all the resources. That is remove the line `[ValidateLength(1,80)]` throughout.
> 
> I will review after that.
> 
> > I don't know if there was but I've tested on 2012 R2 with WMF 5.1 and 2016 and both work. I didn't test on 2008R2 as the module 'RemoteDesktop' doesn't exist nor are there 'Collections' in 2008R2
> 
> Thank you for testing! 2008 R2 is soon unsupported OS too.

I suggest that we keep it as the max length of 80 characters. As this is what is supported.

**Comment by johlju** [comment]
Aha, so there’s a max length. Then I agree we keep it. Is there documentation around that, if so could you add a link to that documentation in the README.md, or add a note for it to the README.me as appropriate?

**Comment by danielboth** [comment]
I had a look at this in my test environment. What happens in the background when we create a new RD Session Collection is that it creates a new instance of the  Win32_RDSHCollection which can be found in the root\cimv2\rdms namespace.

This is also where the limitation for 15 characters comes from. Let's run a test on a session collection with the name "TestCollectionWithVeryLongName"

`
Get-CimInstance -Namespace root\cimv2\rdms -ClassName Win32_RDSHCollection

Alias          : TestCollectionWi
Description    : Test DSC
Name           : TestCollectionWithVeryLongName
`

As we can see in the documentation, the alias property here is the actual key: https://docs.microsoft.com/en-us/windows/win32/termserv/win32-rdshcollection#properties. Not the name property.

So to identify a session collection, we need to use the alias property (which internally, New-RDSessionCollection calls for you). So 15 chars is the limit here.

**Comment by gaelcolas** [comment]
@bendunne, as per @danielboth comment, can you confirm this is a potential problem?
I'd rather not make this change if it's not safe to use in the long run.
/cc @johlju

**Comment by bendunne** [comment]
> @bendunne, as per @danielboth comment, can you confirm this is a potential problem?
> I'd rather not make this change if it's not safe to use in the long run.
> /cc @johlju

Hey so,

I've just tested in a fresh 2016 RDS deployment, if the Collection Name is the same for the first 15 characters. Windows will just add a 1:
image

I've also added the comments to the README file

**Comment by johlju** [comment]
@bendunne Can you confirm that adding a third one will add a '2' to the alias property?

**Comment by bendunne** [comment]
I can but I've already deleted the deployment in Azure and will take another hour of my time to verify. Is not two enough?

Kind Regards,

Ben

On 26 Aug 2019, at 15:20, Johan Ljunggren <notifications@github.com<mailto:notifications@github.com>> wrote:


@bendunne<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbendunne&data=02%7C01%7C%7C2d7faef32c3d4388e32408d72a309189%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637024260389977883&sdata=%2FvktFcJFYTyMesfCFxoEuR%2BebCexGvjvEC2F1gGvk2Y%3D&reserved=0> Can you confirm that adding a third one will add a '2' to the alias property?

**Comment by johlju** [comment]
Ah, sorry about that, but I would really like to know that it actually counts up when there are more than two with the same name. 

Or if there is official documentation explaining that.

**Comment by bendunne** [comment]
> Ah, sorry about that, but I would really like to know that it actually counts up when there are more than two with the same name.
> 
> Or if there is official documentation explaining that.

I couldn't find documentation explaining this. Here is with the third server:


> PS C:\Users\BDTEST> Get-CimInstance -Namespace root\cimv2\rdms -ClassName Win32_RDSHCollection
> 
> 
> Alias          : 1234555555555555
> Description    :
> Name           : 12345555555555555555555555555555555555555555555555555555556664421414173419210878
> Type           : 0
> PSComputerName :
> 
> Alias          : 12345555555555551
> Description    :
> Name           : 12345555555555555555555555555555555555555555555555555555556664421414173419210879
> Type           : 0
> PSComputerName :
> 
> Alias          : 123455555555555512
> Description    :
> Name           : 12345555555555555555555555555555555555555555555555555555556664421414173419210863
> Type           : 0
> PSComputerName 

I'll keep the test environment active until this is resolved.

**Comment by danielboth** [comment]
Hi @bendunne, thank you for all your tests! I verified this also in my test environment on W2016 machines. Also, I created a DSC configuration that deploys 2 collections with long collection names (using a local copy of your branch). That also went fine, I could successfully create two collections with the same name and also test them properly afterwards, where they both reported InDesiredState. 

So it seems that the limitation for this 15 characters is no longer there, so I would be fine with merging this one, as we have now proven that the key identifier on Win32_RDSHCollection (Alias) will stay unique.

**Comment by johlju** [comment]
@bendunne or @danielboth awesome! Thank you so much for testing this. Just one more question, I ask this before, but since you tested again. Do we need to keep a max limit at all, or is 80 chars a hard limit for a collection name? If a collection name can be longer than 80 chars then I don't see the need to limit this at all. What are your thoughts?

**Comment by bendunne** [comment]
> @bendunne and @danielboth awesome! Thank you so much for testing this. Just one more question, I ask this before, but since you tested again. Do we need to keep a max limit at all, or is 80 chars a hard limit for a collection name? If a collection name can be longer than 80 chars then I don't see the need to limit this at all. What are your thoughts?

So the GUI has a limit of 80 Characters but the New-RDSessionCollection command has a limit of 256. Shall I change the validation to 256 characters or just remove it altogether? I guess if we are building a DSC resource we want it to be reliable even in the unlikely use cases.

**Comment by johlju** [comment]
If viewing a collection name that is longer than 80 chars in the GUI, will it be cut? If it will be cut in the GUI then let's keep as-is, but if the GUI can show the known hard-limit of 256 chars then I suggest to change it to that. 🙂:thinking:

**Comment by bendunne** [comment]
> If viewing a collection name that is longer than 80 chars in the GUI, will it be cut? If it will be cut in the GUI then let's keep as-is, but if the GUI can show the known hard-limit of 256 chars then I suggest to change it to that. 🙂🤔

So the GUI limit to enter is 80 however if I set the length of the collection name to 256 chars it will still display this in the GUI. I have updated the files to reflect this.

**Comment by johlju** [comment]
@bendunne thank you for your patience and work on this change! 😃 

@gaelcolas can you merge this as I don't have permission.

**Pull request merged**
