### PR TITLE
xRDSessionDeployment, xRDServer: Fixes for #47 and #50

### LINKED ISSUE #47: xRDSessionDeployment: You cannot call a method on a null-valued expression
### System info (W2016 Azure VM)

``` powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


 [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

```

### Issue 
When calling the 'xRDSessionDeployment' in a 'clean machine', it fails with:
```` powershell
You cannot call a method on a null-valued expression.
At line:80 char:5
+     (Get-TargetResource @PSBoundParameters).SessionHost.ToLower() -ie ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
````
(above info is from loading the resource as function and calling them direct)

The whole thing makes perfect sense, when calling the Get-TargetResource you'll get:
``` powershell
PS C:\Users\devadmin> Get-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
WebAccessServer                                                                                                                                        
SessionHost                                                                                                                                            
ConnectionBroker                         
````
...and indeed; you cannot do a .ToLower() on an empty value...

Looking back in the releases; this code changed since v1.5.0.0 and this bug seems to be there since then.....(ouch?!)

### Solution (proposal)
I do not expect this to be fixed as this code already changed/improved in dev branch.. So I also checked that code. This too contains a bug:
``` Powershell
PS C:\Users\devadmin> Test-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"
Get-Service : Cannot find any service with service name 'RDMS'.
At line:26 char:9
+     if((Get-Service -Name RDMS | Select-Object -ExpandProperty Status ...
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RDMS:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 
WARNING: Failed to start RDMS service. Error: Cannot find any service with service name 'RDMS'.
False
```
The easy fix would be:
``` PowerShell
    # Start service RDMS is needed because otherwise a reboot loop could happen due to
    # the RDMS Service being on Delay-Start by default, and DSC kicks in too quickly after a reboot.
    if((Get-Service -Name RDMS -ErrorAction SilentlyContinue| Select-Object -ExpandProperty Status) -ne 'Running') 
    {
        try
        {
            Start-Service -Name RDMS -ErrorAction Stop
        }
        catch
        {
            Write-Warning "Failed to start RDMS service. Error: $_"
        }
    }
```
But I am unsure why simpler code of earlier versions has expanded to so elaborate one as above... probably the provide better feedback?

### Finally
Kind request; as this resource item is main/core functionality of this DSC module and does not seem to work (you cannot not deploy an RDS environment with v1.5.0.0 or above); please push the next release asap..

### LINKED ISSUE #50: xRDServer: parameter typo GateewayExternalFqdn
https://github.com/PowerShell/xRemoteDesktopSessionHost/blob/df7c4d96c27adae1b72eaa13e07529c40addb1d9/DSCResources/MSFT_xRDServer/MSFT_xRDServer.psm1#L173

### PR DESCRIPTION
**Pull request by danielboth**
#### Pull Request (PR) description
This PR contains the changes from PR #55 from @peppekerstens merged with dev. It fixes some typo's in parameters and a case where, when the RDMS service does not exist, the resource would throw an error.

#### This Pull Request (PR) fixes the following issues

- Fixes #47 
- Fixes #50
- Closes #55

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/58)

### CODE REVIEW

**Comment by danielboth** [comment]
Hi @gaelcolas, mind helping us out merging this one as well?

**Comment by danielboth** [comment]
More than a month ago. @ld0614 any chance you can look into this?

**Comment by danielboth** [comment]
Tagging @johlju for a review. Thanks in advance!

**Comment by johlju** [comment]
@danielboth or @gaelcolas could either of you add `Closes #55` to the PR description so we close the other PR as well when this merges?

@gaelcolas can you please merge this PR.

**Comment by gaelcolas** [comment]
Thanks @danielboth 	& @johlju
I'm just hilighting the Codecoverage diff hit in case you haven't seen it, but will merge anyway.

**Comment by johlju** [comment]
I ignored it since sometimes it gives false negatives. Code coverage report looked okay, and thought the changes made should be covered by existing tests. 

Sure, we could have done TDD and make a (regression) test that fails before making the change, so it shows the change works. :)

**Comment by johlju** [comment]
After looking at the tests again it looks like there were tests made to cover this change. That’s why I ignored the code coverage status check (as it can give false negatives in some scenarios).

**Pull request merged**
