### PR TITLE
xRDSessionDeployment: Get-TargetResource fails when RDMS service does not exist

### LINKED ISSUE #47: xRDSessionDeployment: You cannot call a method on a null-valued expression
### System info (W2016 Azure VM)

``` powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


 [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

```

### Issue 
When calling the 'xRDSessionDeployment' in a 'clean machine', it fails with:
```` powershell
You cannot call a method on a null-valued expression.
At line:80 char:5
+     (Get-TargetResource @PSBoundParameters).SessionHost.ToLower() -ie ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
````
(above info is from loading the resource as function and calling them direct)

The whole thing makes perfect sense, when calling the Get-TargetResource you'll get:
``` powershell
PS C:\Users\devadmin> Get-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
WebAccessServer                                                                                                                                        
SessionHost                                                                                                                                            
ConnectionBroker                         
````
...and indeed; you cannot do a .ToLower() on an empty value...

Looking back in the releases; this code changed since v1.5.0.0 and this bug seems to be there since then.....(ouch?!)

### Solution (proposal)
I do not expect this to be fixed as this code already changed/improved in dev branch.. So I also checked that code. This too contains a bug:
``` Powershell
PS C:\Users\devadmin> Test-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"
Get-Service : Cannot find any service with service name 'RDMS'.
At line:26 char:9
+     if((Get-Service -Name RDMS | Select-Object -ExpandProperty Status ...
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RDMS:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 
WARNING: Failed to start RDMS service. Error: Cannot find any service with service name 'RDMS'.
False
```
The easy fix would be:
``` PowerShell
    # Start service RDMS is needed because otherwise a reboot loop could happen due to
    # the RDMS Service being on Delay-Start by default, and DSC kicks in too quickly after a reboot.
    if((Get-Service -Name RDMS -ErrorAction SilentlyContinue| Select-Object -ExpandProperty Status) -ne 'Running') 
    {
        try
        {
            Start-Service -Name RDMS -ErrorAction Stop
        }
        catch
        {
            Write-Warning "Failed to start RDMS service. Error: $_"
        }
    }
```
But I am unsure why simpler code of earlier versions has expanded to so elaborate one as above... probably the provide better feedback?

### Finally
Kind request; as this resource item is main/core functionality of this DSC module and does not seem to work (you cannot not deploy an RDS environment with v1.5.0.0 or above); please push the next release asap..

### LINKED ISSUE #50: xRDServer: parameter typo GateewayExternalFqdn
https://github.com/PowerShell/xRemoteDesktopSessionHost/blob/df7c4d96c27adae1b72eaa13e07529c40addb1d9/DSCResources/MSFT_xRDServer/MSFT_xRDServer.psm1#L173

### PR DESCRIPTION
**Pull request by peppekerstens**
- Changes to xRDSessionDeployment
  -  When RDMS service does not exist the Get-TargetResource will no longer throw an error (issue #47).

Fixes #47 
Fixes #50 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/48)

### CODE REVIEW

**Comment by johlju** [comment]
@peppekerstens I updated the PR title and PR description to be more descriptive,

**Comment by johlju** [comment]
@peppekerstens thought I just remind you that the tests are failing. You are probably working on it, but just wanted to let you know.

**Comment by peppekerstens** [comment]
will take a look at it this week..

**Comment by peppekerstens** [comment]
sorry for delay. very busy at the moment.

**Comment by peppekerstens** [comment]
C:\Users\..\GitHub\xRemoteDesktopSessionHost [dev ≡]> git rebase
First, rewinding head to replay your work on top of it...
Fast-forwarded dev to refs/remotes/origin/dev.
C:\Users\...\GitHub\xRemoteDesktopSessionHost [dev ≡]> git push --force
Everything up-to-date

am i missing something?

**Comment by peppekerstens** [comment]
just tested on live machine (W16 Azure); tests ok...

**Comment by johlju** [comment]
@peppekerstens You should first fetch the dev branch from the upstream repo.

```
git remote -v
git fetch upstream_remote_name dev
git rebase upstream_remote_name/dev
```

**Comment by peppekerstens** [comment]
i am sorry...in a loop :( 
i know what you/we are trying to achieve; update mine with source/origin. but mine does not seem to comply... 
(my local repo/computer):

git fetch https://github.com/PowerShell/xRemoteDesktopSessionHost.git dev
From https://github.com/PowerShell/xRemoteDesktopSessionHost
 * branch            dev        -> FETCH_HEAD

git rebase https://github.com/PowerShell/xRemoteDesktopSessionHost.git/dev
fatal: Needed a single revision
invalid upstream 'https://github.com/PowerShell/xRemoteDesktopSessionHost.git/dev'

**Comment by peppekerstens** [comment]
ok, did something wrong in the beginning. i cloned instead of forked i guess..

git remote -v
origin  https://github.com/peppekerstens/xRemoteDesktopSessionHost.git (fetch)
origin  https://github.com/peppekerstens/xRemoteDesktopSessionHost.git (push)

oops..

**Comment by peppekerstens** [comment]
so steps should be;
1. get my (local) repo configged right (pointing to right origin)
2. redo rebase
correct?

**Comment by johlju** [comment]
Yes, you are on the right track. Let’s add a new remote pointing to the upstream repo branch 

```
git remote add upstream https://github.com/PowerShell/xRemoteDesktopSessionHost
git fetch upstream dev
git rebase upstream/dev
```

I think that should work.

**Comment by johlju** [comment]
Btw. Cloning is correct. You cloned your fork, which default origin to your forked repository. Then a remote must be added to the upstream. 
If you clone the upstream repo, then origin is pointing to the upstream repo, and a remote must be created to the forked repo. 
Either way is correct. Just have to add and use the correct remote name :)

**Comment by peppekerstens** [comment]
pfff...

**Comment by johlju** [comment]
It looks like you got a lot of extra files (22 in total) that this PR want to change, and most is already in the dev branch 🤔  Maybe your dev need to track the remote dev 🤔 
Could you try to rebase again? 

```
git checkout dev
git branch -u upstream/dev
git fetch upstream dev
git rebase upstream/dev
```

**Comment by peppekerstens** [comment]
it became a mess....

**Pull request closed without merging**
