### PR TITLE
Re-submitting Change to Fix issue with resource in WIndows 10/Server 2016

### PR DESCRIPTION
**Pull request by samcogan82**
Current version check will error with version number greater than 10, and so will not run on server 2016 or windows 10. Changed version check logic to allow this.

Re-submitting with Readme updated this time.

### CODE REVIEW

**Comment by TravisEz13** [comment]
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

**Comment by samcogan82** [comment]
Hello, I am not showing any merge conflicts, however I am not particularly
expert in Git so if there is an issue if you could point me in the right
direction that would be appreciated.

Thanks

Sam

**Comment by samcogan82** [comment]
Ignore the previous email, I have found the issue and resolve the conflict.

**Comment by TravisEz13** [comment]
One issue not addressed

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

Additionally, since the code is repeated, it would be good to move it into a common module.

**Comment by samcogan82** [comment]
I'm a bit confused here, this is a small change to an existing module that
has been produced by Microsoft. As far as I can see there are no existing
tests for this module at all, and it would seem odd to create a test just
for this small item. Similarly as this is one line of code it would see
silly to try and turn this into a module.

**Comment by TravisEz13** [comment]
@samcogan82 
We have [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md) to ensure that we maintain and improve the quality of the resources.

I understand who ever wrote the module did not provide tests, but we need tests to keep quality of the resources up.  I discovered additional issues trying to write tests for this change.  It's not nessecary to fix those issues, but testing your change and filing issues is important.  Adding the test suite encourages others to add tests.

Putting the code in a common location prevents having to fix  the same issue in multiple places.  Looking at the code, this change isn't the only code that needs to be moved to a common location so making this change will encorage others to refactor common code to the common module.

I cloned your repo and tested your change and therefore I have submitted a PR to your repo with suggested changes.

**Comment by samcogan82** [comment]
Thanks Travis,
I understand now, and that is really useful for looking at changes going
forward, thanks for doing that.
I have merged the change so it should be ready to go.

Thanks

Sam

**Comment by TravisEz13** [comment]
Thanks for your contribution!

**Pull request merged**
