### PR TITLE
xRDRemoteApp - Change datatype for UserGroups parameter from [string] to [string[]]

### PR DESCRIPTION
**Pull request by stiwenn**
Update of MSFT_xRDRemoteApp.psm1 and MSFT_xRDRemoteApp.schema.mof in one PR.

This PR should contain 2 files changes executed previously in separate PR's:
https://github.com/PowerShell/xRemoteDesktopSessionHost/pull/18
https://github.com/PowerShell/xRemoteDesktopSessionHost/pull/19

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/22)

### CODE REVIEW

**Comment by bgelens** [comment]
Thanks @stiwenn! 👍 Please sign the contribution license so I can accept the PR. I'll start my review shortly

**Comment by bgelens** [comment]
@stiwenn, Could you update the Readme unreleased and xRDRemoteApp sections. And sign the CLA please :smile: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.schema.mof, line 15 at r1](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/22#-Ko8qFxBEwXDm_3ILiKU:-Ko8qFxBEwXDm_3ILiKV:bamiev) ([raw file](https://github.com/powershell/xremotedesktopsessionhost/blob/971c7aa348642aeac91bac0ab375d4cf6aec0eca/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.schema.mof#L15)):*
> ```
>     [write, Description("Specifies the index within the icon file (specified by the IconPath parameter) where the RemoteApp program's icon can be found.")] uint32 IconIndex;
>     [write, Description("Specifies the path to a file containing the icon to display for the RemoteApp program identified by the Alias parameter.")] string IconPath;
>     [write, Description("Specifies a domain group that can view the RemoteApp in RD Web Access, and in RemoteApp and Desktop Connections. To allow all users to see a RemoteApp program, provide a value of Null.")] string UserGroups[];
> ```

Please update the description to something like, Specifies a or multiple domain group(s) or simular

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/22#-:-Ko8ptfgwch6tcSq5-oY:bqv4ols)*

**Comment by johlju** [comment]
@stiwenn This PR is still waiting for the CLA to be signed. Do you want to sign the CLA? If you know you have signed the CLA already then let me know.
To sign the CLA, please click *Details* on this row.

image

**Comment by johlju** [comment]
Closing this since CLA has not been signed. @stiwenn if you want to continue work on this, please reopen and sign the CLA.

**Pull request closed without merging**
