### PR TITLE
Fix issue where DSC configuration gets into a reboot loop because ses…

### PR DESCRIPTION
**Pull request by KennethVerbeure**
Fix issue where DSC configuration gets into a reboot loop because sessionhost does not match (casing) and RDMS service is not started in time

original issue/fix: https://gallery.technet.microsoft.com/scriptcenter/xRemoteDesktopSessionHost-4a11f27d/view/Discussions

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/24)

### CODE REVIEW

**Comment by ld0614** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/24#-:-Kyr53gz_ZsPc6S8F9-j:bnfp4nl)*

**Comment by ld0614** [comment]
Hi @KennethVerbeure apologies for the delay in looking at your PR, I've only recently become a maintainer, unfortunately a PR I just merged has created a conflict with your branch (#29),  The change was purely style and formatting so should change anything directly relating to your PR.  If your still interested in contributing to the module would you be able to update your PR and add an entry to the unreleased section on the README.md file please?

**Comment by ld0614** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xremotedesktopsessionhost/24#-:-Kzwk0HQ4fDWjYT9_gaL:bnfp4nl)*

**Comment by KennethVerbeure** [comment]
@ld0614 i have no  idea why now i got failing checks, all i did was merge with your DEV branch and edit the readme

**Comment by ld0614** [comment]
Hi @KennethVerbeure The checks are failing as part of my change I enabled codecoverage scoring.  This repo is configured to fail a check if the code coverage score decreases and if your code has a lower test coverage than average (currently 16%).  Unless someone specifically shoots me down (@kwirkykat) as the current unit testing state is so poor I'm ignoring them at the moment.  My plan is to get at least a basic set of unit tests in place prior to enforcing these guidelines.

**Comment by kwirkykat** [comment]
@KennethVerbeure @ld0614 Yes you can completely ignore the 'failed' code coverage check for this repo

**Comment by ld0614** [comment]
Thanks for the Confirmation @kwirkykat and thanks @KennethVerbeure for the contribution

**Pull request merged**
