### PR TITLE
xRDSessionDeployment, xRDServer: fixes

### LINKED ISSUE #47: xRDSessionDeployment: You cannot call a method on a null-valued expression
### System info (W2016 Azure VM)

``` powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


 [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

```

### Issue 
When calling the 'xRDSessionDeployment' in a 'clean machine', it fails with:
```` powershell
You cannot call a method on a null-valued expression.
At line:80 char:5
+     (Get-TargetResource @PSBoundParameters).SessionHost.ToLower() -ie ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
````
(above info is from loading the resource as function and calling them direct)

The whole thing makes perfect sense, when calling the Get-TargetResource you'll get:
``` powershell
PS C:\Users\devadmin> Get-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
WebAccessServer                                                                                                                                        
SessionHost                                                                                                                                            
ConnectionBroker                         
````
...and indeed; you cannot do a .ToLower() on an empty value...

Looking back in the releases; this code changed since v1.5.0.0 and this bug seems to be there since then.....(ouch?!)

### Solution (proposal)
I do not expect this to be fixed as this code already changed/improved in dev branch.. So I also checked that code. This too contains a bug:
``` Powershell
PS C:\Users\devadmin> Test-TargetResource -SessionHost "dev-rdg1.develop.local" -ConnectionBroker "dev-rdb1.develop.local" -WebAccessServer "dev-rdg1.develop.local"
Get-Service : Cannot find any service with service name 'RDMS'.
At line:26 char:9
+     if((Get-Service -Name RDMS | Select-Object -ExpandProperty Status ...
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RDMS:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 
WARNING: Failed to start RDMS service. Error: Cannot find any service with service name 'RDMS'.
False
```
The easy fix would be:
``` PowerShell
    # Start service RDMS is needed because otherwise a reboot loop could happen due to
    # the RDMS Service being on Delay-Start by default, and DSC kicks in too quickly after a reboot.
    if((Get-Service -Name RDMS -ErrorAction SilentlyContinue| Select-Object -ExpandProperty Status) -ne 'Running') 
    {
        try
        {
            Start-Service -Name RDMS -ErrorAction Stop
        }
        catch
        {
            Write-Warning "Failed to start RDMS service. Error: $_"
        }
    }
```
But I am unsure why simpler code of earlier versions has expanded to so elaborate one as above... probably the provide better feedback?

### Finally
Kind request; as this resource item is main/core functionality of this DSC module and does not seem to work (you cannot not deploy an RDS environment with v1.5.0.0 or above); please push the next release asap..

### LINKED ISSUE #50: xRDServer: parameter typo GateewayExternalFqdn
https://github.com/PowerShell/xRemoteDesktopSessionHost/blob/df7c4d96c27adae1b72eaa13e07529c40addb1d9/DSCResources/MSFT_xRDServer/MSFT_xRDServer.psm1#L173

### PR DESCRIPTION
**Pull request by peppekerstens**
#### Pull Request (PR) description
Fixes issues found in resources.

#### This Pull Request (PR) fixes the following issues

Fixes #47 
Fixes #50

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xremotedesktopsessionhost/55)

### CODE REVIEW

**Comment by peppekerstens** [comment]
Hi Johan,

Retry. Again there are more files changed then should be. Problem is that i get presented with untracked or changed files when downloading the xRemoteDesktopSessionHost 'clean' on my machine. Which is very....odd. You can see which ones they are; first commit. When is test other repo's (sqlServerDsc for instance), i have no issues...

Other commits are just a recap of previous work.

**Comment by johlju** [comment]
@peppekerstens Ah, that's because they were committed with the wrong line encoding, with the .gitattributes file fixes!

@ld0614 since you are a maintainer of this repository, could you possible send in a PR merging in the offending files with the correct line encoding? 
Just clone to a new folder and you should see files to stage into a PR.

**Comment by johlju** [comment]
@peppekerstens btw you haven't done anything wrong. The wrong line encodings were there from the beginning. 🙂

**Comment by peppekerstens** [comment]
appveyor build faillure seems to be unrelated to the code (time-out due to hang on certificate error) can you  please re-initiate a build?

**Comment by gaelcolas** [comment]
Now that #57 has been merged, could you try to rebase from the remote's dev branch head and force push to update the PR (and trigger another build)?

**Pull request closed without merging**
